env:
  global:
    - APP_ENV=testing
    - CC_TEST_REPORTER_ID=06bfdffbb28c39bc8e145da160cf166f44e79b04e8c11b927b50dee55360189c

language: php
php:
  - '7.2'

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make lint test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
